routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'Frontend\HomeController@getHome')->name('fe.home');
Route::get('/range', 'Frontend\HomeController@rangeTest');




Route::get('quotation', 'Frontend\QuotationController@index')->name('quotation.get');

Route::post('quotation/store', 'Frontend\QuotationController@store')->name('quotation.store');

Route::get('countries/{iso?}', 'Shared\CountryController@getCountryByIso')->name('country.iso');
Route::get('countries/terminal-points/{iso?}', 'Shared\CountryController@getTerminalPointsByCountryIso')->name('country.iso.terminals');
Route::get('countries/terminal-points/{countryOneIso}/{countryTwoIso}', 'Shared\CountryController@getTerminalPointsByCountriesIso')->name('countries.iso.terminals');
Route::get('{media}/vehicles', 'Shared\TransportController@getVehiclesByMedia')->name('media.vehicles');
Route::get('/map', function () {
    return view('frontend.pages.map-test');
})->middleware(['CheckPermission'])->name('mapp');


Route::get('/image-test', function () {
    return view('test.image-test');
});
Route::post('/image-test', 'Frontend\HomeController@imageTest')->name('image.test');

Route::get('/gopal-courier', function () {
    return view('admin.pages.gopal.courier-form');
})->name('gopal.courier');

Route::get('/gopal-profile', function () {
    return view('');
})->name('gopal.profile');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/login', 'Admin\Auth\AdminLoginController@showLoginForm')->name('getLoginForm');
    Route::post('/login', 'Admin\Auth\AdminLoginController@login')->name('login');
    Route::group(['middleware' => 'LoginMiddleware'], function () {
        Route::post('/logout', 'Admin\Auth\AdminLoginController@logout')->name('logout');
        Route::get('/', function () {
            return view('admin.pages.dashboard.dashboard');
        })->name('dashboard');


        Route::group(['middleware' => 'CheckPermission'], function () {

            //Route Function For Country Module Controll by Admin
            Route::resource('/countries', 'Admin\CountryController');

            Route::group(['prefix' => 'products'], function () {
                //Route Function For Product Module COntroll by Admin
                Route::resource('/categories', 'Admin\ProductCategoryController');
                Route::group(['prefix' => 'categorys'], function () {
                    //Route Function For Product Category Rates Controll by Admin
                    Route::resource('/rates', 'Admin\ProductCategoryRateController');
                    Route::get('/product-category-rate/{productCategory}', 'Admin\ProductCategoryRateController@getProductCategoryRateEdit')->name('getProductCategoryRate');
                    Route::get('/product-category-rate-view/{productCategory}', 'Admin\ProductCategoryRateController@getProductCategoryRateShow')->name('getProductCategoryRateView');
                });
            });
            //Route Function For Terminal Point  Controll by Admin
            Route::resource('/terminalpoints', 'Admin\TerminalPointController');
            Route::group(['prefix' => 'package', 'as' => 'package.'], function () {
                //Route Function For Package Type  Controll by Admin
                Route::resource('/types', 'Admin\PackageTypeController');
                Route::resource('/rates', 'Admin\PackageTypeRateController');
                //Route Function For Package Sensitivities   Controll by Admin
                Route::resource('/sensitivities', 'Admin\PackageSensitivityController');
                Route::group(['prefix' => 'sensitivity', 'as' => 'sensitivity.'], function () {
                    Route::resource('rates', 'Admin\PackageSensitivityRateController');
                });
            });

            //Route Function for Load Information Controll by Admin
            Route::get('/fullload', 'Admin\LoadInformationController@getFillLoad');
            Route::get('/partload', 'Admin\LoadInformationController@getPartLoad');
            Route::get('/partloadshow/{id}', 'Admin\LoadInformationController@getPartLoadView');
            Route::group(['prefix' => 'unit'], function () {
                //Route Function for Unit Category  Controll by Admin
                Route::resource('/categorys', 'Admin\UnitCategoryController');
                Route::resource('/units', 'Admin\UnitController');
            });
        });

        Route::resource('/courier-classes', 'Admin\Courier\CourierClassController');
        //Courier Route List
        Route::group(['prefix'=>'courier'], function(){
            Route::group(['prefix'=>'quantity', 'as' =>'quantity.'], function(){
                Route::resource('/ranges','Admin\Courier\QuantityGroupRangeController');
                Route::resource('/groups', 'Admin\Courier\QuantityGroupController');
                // Route::get('quantity-group-country-show/{coId}/{qaId}', 'Admin\Courier\QuantityGroupCountryController@quantityGroupCountryShow')->name('quantity-group-country-show');
                // Route::get('quantity-group-country-edit/{coId}/{qaId}', 'Admin\Courier\QuantityGroupCountryController@quantityGroupCountryEdit')->name('quantity-group-country-edit');
            });

            Route::resource('/vehicle-time-range', 'Admin\Courier\VehicleTimeTravelRangeController');
            
            // Route::resource('/time-travel-groups', 'Admin\Courier\TimeTravelGroupController');
            // Route::resource('/time-travel-group-rates', 'Admin\Courier\TimeTravelGroupRateController');
            // Route::get('/create-time-travel-group-rate', 'Admin\Courier\TimeTravelGroupRateController@timeTravelGroupData')->name('create-time-travel-group-rate');
            Route::resource('/airports', 'Admin\Courier\AirportController');
            Route::get('/airport-links/getdatacountryone', 'Admin\Courier\AirportLinkController@getDataCountryOne')->name('airport-links.getdatacountryone');
            Route::get('/airport-links/getdatacountrytwo', 'Admin\Courier\AirportLinkController@getDataCountryTwo')->name('airport-links.getdatacountrytwo');
            Route::resource('/airport-links', 'Admin\Courier\AirportLinkController');
            Route::get('/airport-charges/getQuantityGroupRange', 'Admin\Courier\AirportChargeController@getQuantityGroupRangedata')->name('airport-charges.getQuantityGroupRange');
            Route::resource('/airport-charges', 'Admin\Courier\AirportChargeController');
            Route::get('/get-airport-data', 'Admin\Courier\AirportLinkController@getAirpotData')->name('get-airport-data');
            Route::group(['prefix' => 'class', 'as' => 'class.'], function () {
                Route::resource('agencies', 'Admin\Courier\AgencyClassController');

         

                Route::resource('transits', 'Admin\Courier\TransitClassController');
                Route::group(['prefix' => 'charge', 'as' => 'charge.'], function () {
                    Route::resource('agencies', 'Admin\Courier\AgencyClassChargeController');
                    Route::get('/get-quantity-group-data', 'Admin\Courier\AgencyClassChargeController@getQuanityGroupData')->name('get-quantity-group-data');
                    Route::resource('transits', 'Admin\Courier\TransitClassChargeController');
                    Route::get('/get-transit-quantity-group-range', 'Admin\Courier\TransitClassChargeController@getQuanityGroupRange')->name('get-transit-quantity-group-range');
                    Route::get('/get-agency-quantity-group-range', 'Admin\Courier\AgencyClassChargeController@getQuanityGroupRange')->name('get-agency-quantity-group-range');
                });

            });
            Route::get('/agency-transit-vehicle-charge/getQuantityGroupRange', 'Admin\Courier\AgencyTransitVehicleChargeController@getQuantityGroupRangedata')->name('agency-transit-vehicle-charge.getQuantityGroupRange');
            Route::resource('/agency-transit-vehicle-', 'Admin\Courier\AgencyTransitVehicleChargeController');
            Route::resource('/services', 'Admin\Courier\ServiceController');
            Route::get('/admin-charges/getQuantityGroupRange', 'Admin\Courier\AdminChargerController@getQuantityGroupRangedata')->name('admin-charges.getQuantityGroupRange');
            Route::resource('/admin-charges', 'Admin\Courier\AdminChargerController');
            Route::get('/admin-create-charge', 'Admin\Courier\AdminChargerController@adminChargeCreate')->name('admin-create-charge');
            Route::resource('/transits', 'Admin\Courier\TransitController');
            Route::resource('transit-charges', 'Admin\Courier\TransitChargeController');
            Route::resource('transit-vehicle-charges', 'Admin\Courier\TransitVehicleChargeController');

            Route::resource('/agencies', 'Admin\Courier\AgencyController');
            Route::resource('/vehicle-agent-charges', 'Admin\Courier\VehicleAgentChargeController');
            Route::get('/vehicle-agent-charge-get-datas', 'Admin\Courier\VehicleAgentChargeController@vehicleAgentChargeGetData')->name('vehicle-agent-charge-get-datas');
            Route::get('/vehicle-agent-charge-create-datas', 'Admin\Courier\VehicleAgentChargeController@getVehicleAgentCreateData')->name('vehicle-agent-charge-create-datas');
            Route::resource('/agency-links', 'Admin\Courier\AgencyLinkController');
            Route::get('/agency-link-data', 'Admin\Courier\AgencyLinkController@agencyLinkData')->name('agency-link-data');
            Route::resource('/transit-links', 'Admin\Courier\TransitLinkController');

app/Models/AdminCharge.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use PHPUnit\Framework\Constraint\Count;

class AdminCharge extends Model
{
    protected $fillable=['office_id','quantity_group_range_id','rate','currency','status','created_by','updated_by'];
    //
   public function createdBy(){
       return $this->belongsTo(Employee::class, 'created_by')->withDefault();
   }
   public function updatedBy(){
       return $this->belongsTo(Employee::class,'updated_by')->withDefault();
   }
   public function quantityGroupRange(){
       return $this->belongsTo(QuantityGroupRange::class, 'quantity_group_range_id')->withDefault();
   }
   public function office(){
       return $this->belongsTo(Office::class, 'office_id')->withDefault();
   }
   public function getquantityGroupRangeId($quantityGroupId){
        
    return $countryTwoAiroportId=QuantityGroupRange::where('quantity_group_id', $quantityGroupId)->pluck('id')->toArray();
}
public function getpreviousQuantityGroupRangeId($adminId){
    
    return $countryTwoAiroportId=AdminCharge::where('office_id', $adminId)->pluck('quantity_group_range_id')->toArray();
}
public function getPreviousAdminChargeId($adminId){
    
    return $previousAdminCharge=AdminCharge::where('office_id', $adminId)->pluck('id')->toArray();
}

}

app/Http/Controllers/Admin/Courier/AdminChargerController.php
<?php

namespace App\Http\Controllers\Admin\Courier;

use App\Http\Controllers\Controller;
use App\Repositories\Courier\AdminCharge\AdminChargeInterface;
use Illuminate\Http\Request;

use App\ValidationRules\AdminChargeRule;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use DB;

class AdminChargerController extends Controller
{
    private $adminChargeRepository;

    public function __construct(AdminChargeInterface $adminChargeRepository){
            $this->adminChargeRepository=$adminChargeRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $adminCharge=$this->adminChargeRepository->all();
        //return $adminCharge;
        return view('admin.pages.courier.admin-charge.index')->with('admincharges', $adminCharge);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        
       $office=$this->adminChargeRepository->office();
       $quantityGroupName=$this->adminChargeRepository->quantityGroupName();
         //return $quantityGroupName;
        return view('admin.pages.courier.admin-charge.create')
                    ->with('quantityGroupNameData', $quantityGroupName)
                    ->with('offices', $office);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return response()->json($request->all());

         $adminId=$request->airport_link_id;
         $quantityGroupId=$request->quantity_group_id;
         $rule = (new AdminChargeRule($request))->getAdminChargeRules('update',$adminId, $quantityGroupId );
         $validator = Validator::make($request->all(), $rule[0], $rule[1]);
         //return response()->json($request->all());
        
         if ($validator->fails()) {
             if ($request->ajax()){
                 return response()->json(['error'=>$validator->errors()->all()],'422'); 
             }
         }
         
         else{
             
             try {
                 DB::beginTransaction();
                $data = $request->except('_token');
                $airportCharge = $this->adminChargeRepository->save($data);
                  DB::commit();
               session()->flash('flash_message_success', 'Data Store Successfuly!!');
                return response()->json(['success'],'200');            
            } catch (\Exception $exception) {
                DB::rollback();
                return response()->json(['error'=>'Invalite Data !! Please Enter proper data !!'],500);
            }
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $adminCharge=$this->adminChargeRepository->findById($id);
        $adminName=$this->adminChargeRepository->officeName($id);
        //return $adminCharge; 
        return  view('admin.pages.courier.admin-charge.edit')
                    ->with('adminId', $id)
                    ->with('adminName', $adminName)
                    ->with('adminCharges', $adminCharge);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $adminId=$id;
        $quantityGroupId=0;
        $rule = (new AdminChargeRule($request))->getAdminChargeRules('create',$adminId, $quantityGroupId );
        $validator = Validator::make($request->all(), $rule[0], $rule[1]);

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        } 
        DB::beginTransaction();
        try{
        $data=$request->except('_token');
        $airportChargeUpdate=$this->adminChargeRepository->update($data, $id);
        DB::commit();

        session()->flash('flash_message_success','Data Update Successfuly!!');
            return redirect()->route('admin.admin-charges.index');
        }catch (\Exception $exception){
            DB::rollback();
            return redirect()->back()
                ->withInput()
                ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        // DB::beginTransaction();
        // try{
        // $adminCharge=$this->adminChargeRepository->delete($id);
        // DB::commit();
        session()->flash('flash_message_success','Opeartion Successfuly!!');
        return redirect()->route('admin.admin-charges.index');
    // }catch (\Exception $exception){
    //     DB::rollback();
    //     return redirect()->back()
    //         ->withInput()
    //         ->with('flash_message_error', 'Something went wrong ' . $exception->getMessage().'.');
    // }
    }
    public function adminChargeCreate(Request $request){

    $data=$request->except('_token');
    $createData=$this->adminChargeRepository->adminChargeCreateData($data);
    return view('admin.pages.courier.admin-charge.admin-charge-store')
    ->with('transportmedia_id', $data['transport_meida_id'])
    ->with('country_id', $data['country_id'])
    ->with('user_id', $data['user_id'])
    ->with('createData', $createData);
           
    }
    public function getQuantityGroupRangedata(Request $request){
        $data=$request->except('_token');
        $quantityGroupRange=$this->adminChargeRepository->getQuantityGroupRange($data);
        //return response()->json($quantityGroupRange);
         if ($request->ajax()) {
             return view('admin.pages.courier.airport-charge.quantityGroupRangeForm',compact('quantityGroupRange' ))->render();
         }    
    }
}

resources/views/admin/pages/courier/admin-charge/adminChargeForm.blade.php
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
                <table id="myTable" class="table">
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Quantity Group Range</th>
                    <th scope="col">Rate</th>
                    </tr>
                </thead>
                @foreach($quantityGroupRange as $quantityGroupRanges)

                <tbody>
                    <tr>
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>({{$quantityGroupRanges->min_weight }}--{{$quantityGroupRanges->max_weight }})</td>
                    <input type="hidden" value="{{$quantityGroupRanges->id}}" name="quantity_group_range_id[]">
                    <td><input type="text" class="form-control rates" placeholder="Enter  rate"  name="rate[]"></td>
                    <td>
                      <select class="form-control rate_type" name="rate_type[]">
                      <option value="">--Select Rate Type--</option>
                      <option value="fix" selected >Fix</option>
                      <option value="per_kg" {{ $quantityGroupRanges->rate_type == "per_kg" ? 'selected' : '' }}>Per Kg</option>
                      </select>
                    </td>
                    </tr>
                </tbody>
                @endforeach        

                </table>
      </div>
    </div>
  </div>
</div>

resources/views/admin/pages/courier/admin-charge/adminChargeScript.blade.php
<script>  
 function getData(adminCharge){

$.ajax(
            {
                type: 'POST',
                url: "{{route('admin.admin-charges.store')}}",
                data:adminCharge,
                datatype: "json",
            }).done(function (data) {
                //window.location.href = "{{route('admin.admin-charges.index')}}";
                $('#showFlashMessage').removeClass().addClass('alert alert-success').show().empty().html('Data Created Successfully');
        }).fail(function (data) {
            if(data.status==500){
                $('#errorMessage').show().html(data.responseJSON.error);
            }
            console.log(data.responseJSON.error);
            if(data.status==422){
                var errorString = "<ol type='1'>";
            for (error in data.responseJSON.error) {
                errorString += "<li>" + data.responseJSON.error[error] + "</li>";
            }
            errorString += "</ol>";
        
            $('#errorMessage').show().html(errorString);
            }
        });
    }

    $('#submitted').on('click',function(e){
        e.preventDefault();
        let adminCharge=$('#admincharges').serialize();
        getData(adminCharge);
    });
    $('#errorMessage').hide();
    $('#showFlashMessage').hide();


function getQuantityGroupRange(getQuantityGroupRangedata){

$.ajax(
            {
                type: 'GET',
                url: "{{route('admin.admin-charges.getQuantityGroupRange')}}",
                data:getQuantityGroupRangedata,
                datatype: "json",
            }).done(function (data) {
                $("#dynamic_content").empty().html(data);
        }).fail(function (customError) {
            console.log(customError);
        });
    }

    $('#quantity_group_id').on('click',function(e){
        e.preventDefault();
        let getQuantityGroupRangedata=$('#admincharges').serialize();
        getQuantityGroupRange(getQuantityGroupRangedata);
    });
 </script>

resources/views/admin/pages/courier/admin-charge/create.blade.php
@extends('admin.layouts.app')
@section('title','Dashboard')
@section('content')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.admin-charges.index')}}"> Admin Charge</a></li>
    <li class="breadcrumb-item active">Create</li>
@endsection
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="alert alert-danger"  role="alert" id="errorMessage"></div>
        <div class="alert alert-success"  role="alert" id="showFlashMessage"></div>
        <form action="" method="" id="admincharges" enctype="multipart/form-data">
                    {{ csrf_field() }}
                <div class="form-group">
                    <label class="control-label" >Office</label>
                    <select class="form-control" name="office_id">
                    <option disabled selected value="">--Select office--</option>
                        @foreach($offices as $office)
                    <option value="{{$office->id}}">{{$office->name}}</option>
                    @endforeach
                    </select>
                    
                </div>
                <div class="form-group">
                    <label class="control-label" >Quantity Group Name</label>
                    <select class="form-control" name="quantity_group_id" id="quantity_group_id">
                        @foreach($quantityGroupNameData as $quantityGroupNameData)
                    <option value="{{$quantityGroupNameData->id}}">{{$quantityGroupNameData->group_name}}</option>
                    @endforeach
                    </select>
                    
                </div>
                <div class="form-group">
                        <div id="dynamic_content"></div>
                    </div>
                    <div class="form-group">
                <input type="submit" id="submitted" class="btn btn-success"
                value="Publish">
                </div>

        </form>
      </div>
    </div>
  </div>
</div>
@endsection
@push('scripts')
@include('admin.pages.courier.admin-charge.adminChargeScript');
@endpush

resources/views/admin/pages/courier/admin-charge/edit.blade.php
@extends('admin.layouts.app')
@section('title','Admin charge')

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.admin-charges.index')}}">Admin Charge</a></li>
    <li class="breadcrumb-item active">@foreach($adminName as $adminNames)
        {{$adminNames->name}}
        @endforeach</li>
@endsection

@section('content')

@include('error-messages.message')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive mt-4">
                @if(count($adminCharges) > 0) 
                    <form method="POST" action="{{route('admin.admin-charges.update', $adminId)}}" enctype="multipart/form-data" >
                    <input type="hidden" name="_method" value="PUT">
                    {{ csrf_field() }}
                    <table  class="table">
                        <thead>
                        <tr>
                        <th scope="col"> ID </th>
                        <th scope="col"> Quantity Group Name  </th>
                        <th scope="col"> Rate </th>
                        <th scope="col"> Rate Type </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                       
                                        
                        @foreach($adminCharges as $adminCharge)
                        <td>{{$loop->iteration}}</td>
                        <td>{{$adminCharge->groupName}}({{$adminCharge->min_weight}}-{{$adminCharge->max_weight}})</td>
                        <input type="hidden" name="id[]" class="form-control" value="{{$adminCharge->id}}">
                        <input type="hidden" name="quantity_group_range_id[]" class="form-control" value="{{$adminCharge->quantityGroupId}}">

                        <td>
                            <input type="number" name="rate[]" class="form-control" value="{{$adminCharge->rate}}">
                        </td>
                        <td>
                            <select name="rate_type[]" class="form-control">
                                @if($adminCharge->rate_type=='fix'){
                                    <option value="fix">Fix</option>
                                    <option value="per_kg">Per Kg</option>
                                }
                                @else{
                                    <option value="per_kg">Per Kg</option>
                                    <option value="fix">Fix</option>
                                }
                                @endif
                               
                               
                            </select>
                            </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <div class="form-group">
                    <input type="submit"  class="btn btn-success"
                     value="Update">
                        
                    </form>
                    @else
                        <p>There is No data !! please Create charge to click button </p>
                            <a href="{{route('admin.admin-charges.create', $adminId)}}" class="btn btn-info m-r-10">Create charge</a>
                    
                     @endif
                </div>
            </div>
        </div>
    </div>


</div>
    

    
@endsection

resources/views/admin/pages/courier/admin-charge/index.blade.php
@extends('admin.layouts.app')
@section('title','Admin Charge')

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.admin-charges.index')}}">Admin Charge</a></li>
    <li class="breadcrumb-item active">View</li>
@endsection

@section('content')

@include('error-messages.message')
    <div class="row">
    <div class="col-lg-12 text-right">
        <a href="{{route('admin.admin-charges.create')}}" class="btn btn-success m-b-10">Create</a>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive mt-4">
                    <table id="myTable" class="table">
                        <thead>
                        <tr>
                        <th scope="col"> ID </th>
                        <th scope="col">User</th>
                        <th scope="col"> Action </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($admincharges as $admincharge) 
                        <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>
                            {{$admincharge->office->name}}
                        </td>
                            <td class="table-flex">
                                    <a href="{{route('admin.admin-charges.edit', $admincharge->office_id)}}" class="btn btn-warning m-r-10"><i class="far fa-edit"></i></a>
                                    <!-- <form action="{{ route('admin.admin-charges.destroy', $admincharge->id)}}" method="post">
                                        {{ csrf_field() }}
                                        @method('DELETE')
                                        @if($admincharge->status==0)
                                        <button type="submit" class="btn btn-success">Activate</button>
                                        @else
                                            <button type="submit" class="btn btn-danger">Deactivate</button>
                                        @endif
                                    </form> -->
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


</div>
    

    
@endsection