routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'Frontend\HomeController@getHome')->name('fe.home');
Route::get('/range', 'Frontend\HomeController@rangeTest');




Route::get('quotation', 'Frontend\QuotationController@index')->name('quotation.get');

Route::post('quotation/store', 'Frontend\QuotationController@store')->name('quotation.store');

Route::get('countries/{iso?}', 'Shared\CountryController@getCountryByIso')->name('country.iso');
Route::get('countries/terminal-points/{iso?}', 'Shared\CountryController@getTerminalPointsByCountryIso')->name('country.iso.terminals');
Route::get('countries/terminal-points/{countryOneIso}/{countryTwoIso}', 'Shared\CountryController@getTerminalPointsByCountriesIso')->name('countries.iso.terminals');
Route::get('{media}/vehicles', 'Shared\TransportController@getVehiclesByMedia')->name('media.vehicles');
Route::get('/map', function () {
    return view('frontend.pages.map-test');
})->middleware(['CheckPermission'])->name('mapp');


Route::get('/image-test', function () {
    return view('test.image-test');
});
Route::post('/image-test', 'Frontend\HomeController@imageTest')->name('image.test');

Route::get('/gopal-courier', function () {
    return view('admin.pages.gopal.courier-form');
})->name('gopal.courier');

Route::get('/gopal-profile', function () {
    return view('');
})->name('gopal.profile');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/login', 'Admin\Auth\AdminLoginController@showLoginForm')->name('getLoginForm');
    Route::post('/login', 'Admin\Auth\AdminLoginController@login')->name('login');
    Route::group(['middleware' => 'LoginMiddleware'], function () {
        Route::post('/logout', 'Admin\Auth\AdminLoginController@logout')->name('logout');
        Route::get('/', function () {
            return view('admin.pages.dashboard.dashboard');
        })->name('dashboard');


        Route::group(['middleware' => 'CheckPermission'], function () {

            //Route Function For Country Module Controll by Admin
            Route::resource('/countries', 'Admin\CountryController');

            Route::group(['prefix' => 'products'], function () {
                //Route Function For Product Module COntroll by Admin
                Route::resource('/categories', 'Admin\ProductCategoryController');
                Route::group(['prefix' => 'categorys'], function () {
                    //Route Function For Product Category Rates Controll by Admin
                    Route::resource('/rates', 'Admin\ProductCategoryRateController');
                    Route::get('/product-category-rate/{productCategory}', 'Admin\ProductCategoryRateController@getProductCategoryRateEdit')->name('getProductCategoryRate');
                    Route::get('/product-category-rate-view/{productCategory}', 'Admin\ProductCategoryRateController@getProductCategoryRateShow')->name('getProductCategoryRateView');
                });
            });
            //Route Function For Terminal Point  Controll by Admin
            Route::resource('/terminalpoints', 'Admin\TerminalPointController');
            Route::group(['prefix' => 'package', 'as' => 'package.'], function () {
                //Route Function For Package Type  Controll by Admin
                Route::resource('/types', 'Admin\PackageTypeController');
                Route::resource('/rates', 'Admin\PackageTypeRateController');
                //Route Function For Package Sensitivities   Controll by Admin
                Route::resource('/sensitivities', 'Admin\PackageSensitivityController');
                Route::group(['prefix' => 'sensitivity', 'as' => 'sensitivity.'], function () {
                    Route::resource('rates', 'Admin\PackageSensitivityRateController');
                });
            });

            //Route Function for Load Information Controll by Admin
            Route::get('/fullload', 'Admin\LoadInformationController@getFillLoad');
            Route::get('/partload', 'Admin\LoadInformationController@getPartLoad');
            Route::get('/partloadshow/{id}', 'Admin\LoadInformationController@getPartLoadView');
            Route::group(['prefix' => 'unit'], function () {
                //Route Function for Unit Category  Controll by Admin
                Route::resource('/categorys', 'Admin\UnitCategoryController');
                Route::resource('/units', 'Admin\UnitController');
            });
        });

        Route::resource('/courier-classes', 'Admin\Courier\CourierClassController');
        //Courier Route List
        Route::group(['prefix'=>'courier'], function(){
            Route::group(['prefix'=>'quantity', 'as' =>'quantity.'], function(){
                Route::resource('/ranges','Admin\Courier\QuantityGroupRangeController');
                Route::resource('/groups', 'Admin\Courier\QuantityGroupController');
                // Route::get('quantity-group-country-show/{coId}/{qaId}', 'Admin\Courier\QuantityGroupCountryController@quantityGroupCountryShow')->name('quantity-group-country-show');
                // Route::get('quantity-group-country-edit/{coId}/{qaId}', 'Admin\Courier\QuantityGroupCountryController@quantityGroupCountryEdit')->name('quantity-group-country-edit');
            });

            Route::resource('/vehicle-time-range', 'Admin\Courier\VehicleTimeTravelRangeController');
            
            // Route::resource('/time-travel-groups', 'Admin\Courier\TimeTravelGroupController');
            // Route::resource('/time-travel-group-rates', 'Admin\Courier\TimeTravelGroupRateController');
            // Route::get('/create-time-travel-group-rate', 'Admin\Courier\TimeTravelGroupRateController@timeTravelGroupData')->name('create-time-travel-group-rate');
            Route::resource('/airports', 'Admin\Courier\AirportController');
            Route::get('/airport-links/getdatacountryone', 'Admin\Courier\AirportLinkController@getDataCountryOne')->name('airport-links.getdatacountryone');
            Route::get('/airport-links/getdatacountrytwo', 'Admin\Courier\AirportLinkController@getDataCountryTwo')->name('airport-links.getdatacountrytwo');
            Route::resource('/airport-links', 'Admin\Courier\AirportLinkController');
            Route::get('/airport-charges/getQuantityGroupRange', 'Admin\Courier\AirportChargeController@getQuantityGroupRangedata')->name('airport-charges.getQuantityGroupRange');
            Route::resource('/airport-charges', 'Admin\Courier\AirportChargeController');
            Route::get('/get-airport-data', 'Admin\Courier\AirportLinkController@getAirpotData')->name('get-airport-data');
            Route::group(['prefix' => 'class', 'as' => 'class.'], function () {
                Route::resource('agencies', 'Admin\Courier\AgencyClassController');

         

                Route::resource('transits', 'Admin\Courier\TransitClassController');
                Route::group(['prefix' => 'charge', 'as' => 'charge.'], function () {
                    Route::resource('agencies', 'Admin\Courier\AgencyClassChargeController');
                    Route::get('/get-quantity-group-data', 'Admin\Courier\AgencyClassChargeController@getQuanityGroupData')->name('get-quantity-group-data');
                    Route::resource('transits', 'Admin\Courier\TransitClassChargeController');
                    Route::get('/get-transit-quantity-group-range', 'Admin\Courier\TransitClassChargeController@getQuanityGroupRange')->name('get-transit-quantity-group-range');
                    Route::get('/get-agency-quantity-group-range', 'Admin\Courier\AgencyClassChargeController@getQuanityGroupRange')->name('get-agency-quantity-group-range');
                });

            });
            Route::get('/agency-transit-vehicle-charge/getQuantityGroupRange', 'Admin\Courier\AgencyTransitVehicleChargeController@getQuantityGroupRangedata')->name('agency-transit-vehicle-charge.getQuantityGroupRange');
            Route::resource('/agency-transit-vehicle-', 'Admin\Courier\AgencyTransitVehicleChargeController');
            Route::resource('/services', 'Admin\Courier\ServiceController');
            Route::get('/admin-charges/getQuantityGroupRange', 'Admin\Courier\AdminChargerController@getQuantityGroupRangedata')->name('admin-charges.getQuantityGroupRange');
            Route::resource('/admin-charges', 'Admin\Courier\AdminChargerController');
            Route::get('/admin-create-charge', 'Admin\Courier\AdminChargerController@adminChargeCreate')->name('admin-create-charge');
            Route::resource('/transits', 'Admin\Courier\TransitController');
            Route::resource('transit-charges', 'Admin\Courier\TransitChargeController');
            Route::resource('transit-vehicle-charges', 'Admin\Courier\TransitVehicleChargeController');

            Route::resource('/agencies', 'Admin\Courier\AgencyController');
            Route::resource('/vehicle-agent-charges', 'Admin\Courier\VehicleAgentChargeController');
            Route::get('/vehicle-agent-charge-get-datas', 'Admin\Courier\VehicleAgentChargeController@vehicleAgentChargeGetData')->name('vehicle-agent-charge-get-datas');
            Route::get('/vehicle-agent-charge-create-datas', 'Admin\Courier\VehicleAgentChargeController@getVehicleAgentCreateData')->name('vehicle-agent-charge-create-datas');
            Route::resource('/agency-links', 'Admin\Courier\AgencyLinkController');
            Route::get('/agency-link-data', 'Admin\Courier\AgencyLinkController@agencyLinkData')->name('agency-link-data');
            Route::resource('/transit-links', 'Admin\Courier\TransitLinkController');

app/Models/ProductCategoryRate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProductCategoryRate extends Model
{
    protected $fillable = ['country_id','product_category_id','min_weight','max_weight','rate'];

    // Get the country that owns the rate.
    public function country(){
        return $this->belongsTo(Country::class, 'country_id')->withDefault();
    }

    // Get the product category that owns the rate.
    public function productCategory(){
        return $this->belongsTo(ProductCategory::class, 'product_category_id')->withDefault();
    }

    //get shipment rate for the product category
    public function shipment(){
        return $this->hasMany(Shipment::class,'product_category_rate_id');
    }
}

app/Http/Controllers/Admin/ProductCategoryRateController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ProductCategoryRate;
use App\Models\ProductCategory;
use App\Models\Country;

use App\ValidationRules\CategoryRateRule;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use App\Repositories\ProductCategoryRate\CategoryRateInterface;
use App\Traits\WeightRangeService;
use App\Services\CompareWeightRangeService;
use Exception;

class ProductCategoryRateController extends Controller
{
    use WeightRangeService;

    private $catergoryRateRepository;

    public function __construct(CategoryRateInterface $catergoryRateRepository){
            $this->catergoryRateRepository=$catergoryRateRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categoryRates=$this->catergoryRateRepository->all();
        return view('admin.pages.product-category-rate.index')->with('categoryRate', $categoryRates);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categorys=$this->catergoryRateRepository->findByFlag();
        return view('admin.pages.product-category-rate.create')

        ->with('category', $categorys);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      
        $validator = Validator::make($request->all(),(new CategoryRateRule($request))->getCategoryRateValidationRules('create'));

        if ($validator->fails()) {
           // session()->flash('flash_message_error','Please enter  Integer only !!');
            return redirect()->back()
                 ->withErrors($validator)
                 ->withInput();
        }
        $data=$request->except('_token');
        $min = $data['min_weight'];
        $max =$data['max_weight'];

        try{

            $max=$this->testWeightRange($min,$max);
            $categoryRate=$this->catergoryRateRepository->save($data, $min, $max);
        }catch (\Exception $exception){
            session()->flash('flash_message_error',$exception->getMessage());
            return redirect()->back();
        }
        
        if($categoryRate){
            //return redirect()->route('admin.rate.index')->with('message', 'Data Create Successfuly!');
                session()->flash('flash_message_success','Data Store Successfuly!!');
                return redirect()->route('admin.rates.index');
        }
        else{
                session()->flash('flash_message_error','Error!!');
                return redirect()->route('admin.rates.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($productCategoryId)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($caId, $coId )
    {
       
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),(new CategoryRateRule($request))->getCategoryRateValidationRules('update'));

        if ($validator->fails()) {
            //session()->flash('flash_message_error','Please enter  Integer only !!');
            return redirect()->back()
                 ->withErrors($validator)
                 ->withInput();
        }
        $data=$request->except('_token');
        $min = $data['min_weight'];
        $max =$data['max_weight'];

        try{
            $max=$this->testWeightRange($min,$max);
            $this->catergoryRateRepository->update($data, $min, $max, $id);
            $this->catergoryRateRepository->deletePerviousData($data);
                session()->flash('flash_message_success','Data Update Successfuly!!');
                return redirect()->route('admin.rates.index');
        }catch (\Exception $exception){
            session()->flash('flash_message_error',$exception->getMessage());
            return redirect()->back()
                 ->withErrors($validator)
                 ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function getProductCategoryRateEdit($productCategoryId){
        $categoryRates=$this->catergoryRateRepository->findByProductCategoryId($productCategoryId);
        $categorys=$this->catergoryRateRepository->findByFlag();
  
        return view('admin.pages.product-category-rate.edit')
     
        ->with('category', $categorys)
        ->with('categoryRates', $categoryRates);
    }
    public function getProductCategoryRateShow($productCategoryId){
        $categoryRates=$this->catergoryRateRepository->findByProductCategoryId($productCategoryId);
        // $categoryRateSingle=$this->catergoryRateRepository->findByCountryIdFirst($coId, $caId);
        return view('admin.pages.product-category-rate.show')
                ->with('categoryRates', $categoryRates);
    }
}

resources/views/admin/pages/product-category-rate/categoryScript.blade.php
<script>  
 $(document).ready(function(){  
      var i=1;  
      $('#add').click(function(){  
           i++;  
           $('#dynamic_field').append('<tr id="row'+i+'"><td class="pad-cus-pro-cat"><input type="text" name="min_weight[]" placeholder="Enter  minimum weight" class="form-control min-weight"  }}"/></td><td><input type="text" name="max_weight[]" placeholder="Enter maxmium weight" class="form-control max-weight" }}" /></td><br><td><input type="text" name="rate[]" placeholder="Enter  rate" class="form-control rate" }}" /></td><td><button type="button" name="remove" id="'+i+'" class="btn btn-danger btn_remove">X</button></td></tr>');  
      });  
      $(document).on('click', '.btn_remove', function(){  
           var button_id = $(this).attr("id");   
           $('#row'+button_id+'').remove();  
      });  
    //   $('#submit').click(function(){            
    //        $.ajax({  
    //             url:"{{route('admin.rates.store')}}",  
    //             method:"POST",  
    //             data:$('#add_name').serialize(),  
    //             success:function(data)  
    //             {  
    //                  console.log(data);  
    //                  $('#add_name')[0].reset();  
    //             }  
    //        });  
    //   });  
 });  
 </script>

resources/views/admin/pages/product-category-rate/create.blade.php
@extends('admin.layouts.app')
@section('title','Dashboard')
@section('content')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.rates.index')}}"> Product Category Rates</a></li>
    <li class="breadcrumb-item active">Create</li>
   
@endsection
@include('error-messages.message')
<form action="{{route('admin.rates.store')}}" method="POST"  enctype="multipart/form-data" id="add_name" >
            {{ csrf_field() }}
            @include('admin.pages.product-category-rate.form', [$formMode="Publish"])
</form>
@endsection
@push('scripts')
    @include('admin.pages.product-category-rate.categoryScript');
@endpush

resources/views/admin/pages/product-category-rate/edit.blade.php
@extends('admin.layouts.app')
@section('title','Dashboard')
@section('content')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.rates.index')}}"> Product Category Rates</a></li>
    <li class="breadcrumb-item active">Edit</li>
    @include('error-messages.message')
@endsection
<form action="{{route('admin.rates.update', $categoryRates[0]->Country->id)}}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="PUT">
            @include('admin.pages.product-category-rate.editForm', [$formMode="Edit"])
</form>
@endsection
@push('scripts')
    @include('admin.pages.product-category-rate.categoryScript');
@endpush

resources/views/admin/pages/product-category-rate/editForm.blade.php
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body"> 
                <div class="form-group">
                    <label class="control-label" >Category</label>
                    <select class="form-control" name="product_category_id" >
                    <option value="">--select an option--</option>
                        @foreach($category as $categorys)
                        <option value="{{$categorys->id}}"<?php if(isset($categoryRates[0]) && $categoryRates[0]->ProductCategory->id == $categorys->id ) echo 'selected'; ?>
                    >{{$categorys->name}}</option>
                        @endforeach
        
                    </select>
                </div>
                @foreach($categoryRates as $categoryRate)
                <table class="table" >
                <tr> 
                    <td class="d-none"><input type="hidden" class="form-control min-weight" value="{{$categoryRate->id}}"  name="deleteId[]"  ></td> 
                    <td class="pad-cus-pro-cat"><input type="text" class="form-control min-weight" value="{{$categoryRate->min_weight}}" placeholder="Enter  minimum weight"  name="min_weight[]"  ></td>
                    <td class="pad-cus-pro-cat"><input type="text" class="form-control max-weight" value="{{$categoryRate->max_weight}}" placeholder="Enter  maxmium weight"  name="max_weight[]" ></td>
                    <td class="pad-cus-pro-cat"><input type="text" class="form-control rates" value="{{$categoryRate->rate}}" placeholder="Enter  rate"  name="rate[]" ></td>
                </tr>
                </table>
                @endforeach
                <table class="table" id="dynamic_field">
                <tr>
                    
                </tr>
                </table>
                
                <button type="button" name="add" id="add" class="btn btn-success btn-center"><i class="fa fa-plus"></i>   Add More</button>
                
                <div class="form-group">
                    <input type="submit" id="submit" name="submit" class="btn btn-success" value="Update">
                </div>
            </div>
        </div>
    </div>
</div>
        

resources/views/admin/pages/product-category-rate/form.blade.php
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="control-label" >Category</label>
                        <select class="form-control" name="product_category_id" >
                        <option value="">--select an option--</option>
                            @foreach($category as $categorys)
                                <option value="{{$categorys->id}}"
                                {{$categorys->id == old('product_category_id') ? 'selected' : ''}}
                                    <?php if(isset($categoryRate) && $categoryRate->ProductCategory->id == $categorys->id ) echo 'selected'; ?>
                                    >
                                    {{$categorys->name}}
                                </option>
                                
                            @endforeach
            
                        </select>
                    </div>
                    <table class="table" id="dynamic_field">
                    <tr>
                        <td><input type="text" class="form-control min-weight" placeholder="Enter  minimum weight"  name="min_weight[]"  ></td>
                        <td><input type="text" class="form-control max-weight" placeholder="Enter  maxmium weight"  name="max_weight[]" ></td>
                        <td><input type="text" class="form-control rates" placeholder="Enter  rate"  name="rate[]" ></td>
                    </tr>
                    </table>
                    
                    <button style="margin-left: 350px;" type="button" name="add" id="add" class="btn btn-success">Add More</button>
                    
                    <div class="form-group">
                    <input type="submit" id="submit" name="submit" class="btn btn-success"
                    value="{{ $formMode == 'Publish' ? 'Publish' : 'Update'}}">
                    </div>
                </div>
            </div>
        </div>
    </div>
       

resources/views/admin/pages/product-category-rate/index.blade.php
@extends('admin.layouts.app')
@section('title','Dashboard')
@section('content')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.rates.index')}}"> Product Category Rates</a></li>
    <li class="breadcrumb-item active">View</li>
@endsection
@include('error-messages.message')
<div class="row">
    <div class="col-lg-12 text-right">
        <a href="{{route('admin.rates.create')}}" class="btn btn-success m-b-10">Create</a>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive mt-4">
                    <table id= "myTable" class="table">
        
                        <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Country</th>
                                <th scope="col">Product Category</th>
                                <th scope="col">Rates</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($categoryRate as $categoryRates)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$categoryRates->Country->name}}</td>
                                    <td>{{$categoryRates->ProductCategory->name}}</td>
                                    <td>
                                    <a href="{{ route('admin.getProductCategoryRateView', $categoryRates->product_category_id )}}" class="btn btn-info">View</a>
                                    <a href="{{ route('admin.getProductCategoryRate', $categoryRates->product_category_id) }}" class="btn btn-warning">Edit</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
    </div>
@endsection

resources/views/admin/pages/product-category-rate/show.blade.php
@extends('admin.layouts.app')
@section('title','Dashboard')
@section('content')
@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
<li class="breadcrumb-item"><a href="{{route('admin.rates.index')}}"> Product Category rates</a></li>
<li class="breadcrumb-item active">{{$categoryRates[0]->Country->name}}</li>
@endsection

<div class="row">
    <div class="col-lg-12 text-right">
        <a href="{{route('admin.rates.create')}}" class="btn btn-success m-b-10">Create</a>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <!-- <div class="table-responsive">
                        <table class="table">
                            <tr>
                                <th>Country</th>
                                <td>{{$categoryRates[0]->Country->name}}</td>
                            </tr>
                            <tr>
                                <th>Product Category</th>
                                <td>{{$categoryRates[0]->ProductCategory->name}}</td>
                            </tr>
                            @foreach($categoryRates as $categoryRate)
                            <tr>
                                <th>Maxmium Weight</th>
                                <td>{{$categoryRate->max_weight}}</td>
                            </tr>
                            <tr>
                                <th>Minimum Weight</th>
                                <td>{{$categoryRate->min_weight}}</td>
                            </tr>
                            <tr>
                                <th>Rate</th>
                                <td>{{$categoryRate->rate}}</td>
                            </tr>
                            @endforeach
                        </table>
                    </div> -->
                <div class="country-div-list">
                    <ul class="weight-gain-ul">
                        <li>
                            <h4>Country : </h4>
                            <h6>{{$categoryRates[0]->Country->name}}</h6>
                        </li>
                        <li>
                            <h4>Product Category : </h4>
                            <h6>{{$categoryRates[0]->ProductCategory->name}}</h6>
                        </li>
                        @foreach($categoryRates as $categoryRate)
                        <li>
                            <h4>Maxmium Weight : </h4>
                            <h6>{{$categoryRate->max_weight}}</h6>
                        </li>
                        <li>
                            <h4>Minimum Weight : </h4>
                            <h6>{{$categoryRate->min_weight}}</h6>
                        </li>
                        <li>
                            <h4>Rate : </h4>
                            <h6>{{$categoryRate->rate}}</h6>
                        </li>
                        @endforeach 
                    </ul>
                </div>
                <div class="form-btn">
                    <a href="{{ route('admin.rates.edit', $categoryRate->id) }}" class="btn btn-warning">Edit</a>
                </div>
            </div>
        </div>
    </div>

</div>
<div class="row">
</div>

@endsection