routes/web.php
        Route::group(['prefix'=>'courier'], function(){
            Route::group(['prefix'=>'quantity', 'as' =>'quantity.'], function(){
                Route::resource('/ranges','Admin\Courier\QuantityGroupRangeController');
                Route::resource('/groups', 'Admin\Courier\QuantityGroupController');
                // Route::get('quantity-group-country-show/{coId}/{qaId}', 'Admin\Courier\QuantityGroupCountryController@quantityGroupCountryShow')->name('quantity-group-country-show');
                // Route::get('quantity-group-country-edit/{coId}/{qaId}', 'Admin\Courier\QuantityGroupCountryController@quantityGroupCountryEdit')->name('quantity-group-country-edit');
            });

            Route::resource('/vehicle-time-range', 'Admin\Courier\VehicleTimeTravelRangeController');
            
            // Route::resource('/time-travel-groups', 'Admin\Courier\TimeTravelGroupController');
            // Route::resource('/time-travel-group-rates', 'Admin\Courier\TimeTravelGroupRateController');
            // Route::get('/create-time-travel-group-rate', 'Admin\Courier\TimeTravelGroupRateController@timeTravelGroupData')->name('create-time-travel-group-rate');
            Route::resource('/airports', 'Admin\Courier\AirportController');
            Route::get('/airport-links/getdatacountryone', 'Admin\Courier\AirportLinkController@getDataCountryOne')->name('airport-links.getdatacountryone');
            Route::get('/airport-links/getdatacountrytwo', 'Admin\Courier\AirportLinkController@getDataCountryTwo')->name('airport-links.getdatacountrytwo');
            Route::resource('/airport-links', 'Admin\Courier\AirportLinkController');
            Route::get('/airport-charges/getQuantityGroupRange', 'Admin\Courier\AirportChargeController@getQuantityGroupRangedata')->name('airport-charges.getQuantityGroupRange');
            Route::resource('/airport-charges', 'Admin\Courier\AirportChargeController');
            Route::get('/get-airport-data', 'Admin\Courier\AirportLinkController@getAirpotData')->name('get-airport-data');
            Route::group(['prefix' => 'class', 'as' => 'class.'], function () {
                Route::resource('agencies', 'Admin\Courier\AgencyClassController');

         

                Route::resource('transits', 'Admin\Courier\TransitClassController');
                Route::group(['prefix' => 'charge', 'as' => 'charge.'], function () {
                    Route::resource('agencies', 'Admin\Courier\AgencyClassChargeController');
                    Route::get('/get-quantity-group-data', 'Admin\Courier\AgencyClassChargeController@getQuanityGroupData')->name('get-quantity-group-data');
                    Route::resource('transits', 'Admin\Courier\TransitClassChargeController');
                    Route::get('/get-transit-quantity-group-range', 'Admin\Courier\TransitClassChargeController@getQuanityGroupRange')->name('get-transit-quantity-group-range');
                    Route::get('/get-agency-quantity-group-range', 'Admin\Courier\AgencyClassChargeController@getQuanityGroupRange')->name('get-agency-quantity-group-range');
                });

            });
            Route::get('/agency-transit-vehicle-charge/getQuantityGroupRange', 'Admin\Courier\AgencyTransitVehicleChargeController@getQuantityGroupRangedata')->name('agency-transit-vehicle-charge.getQuantityGroupRange');
            Route::resource('/agency-transit-vehicle-', 'Admin\Courier\AgencyTransitVehicleChargeController');
            Route::resource('/services', 'Admin\Courier\ServiceController');
            Route::get('/admin-charges/getQuantityGroupRange', 'Admin\Courier\AdminChargerController@getQuantityGroupRangedata')->name('admin-charges.getQuantityGroupRange');
            Route::resource('/admin-charges', 'Admin\Courier\AdminChargerController');
            Route::get('/admin-create-charge', 'Admin\Courier\AdminChargerController@adminChargeCreate')->name('admin-create-charge');
            Route::resource('/transits', 'Admin\Courier\TransitController');
            Route::resource('transit-charges', 'Admin\Courier\TransitChargeController');
            Route::resource('transit-vehicle-charges', 'Admin\Courier\TransitVehicleChargeController');

            Route::resource('/agencies', 'Admin\Courier\AgencyController');
            Route::resource('/vehicle-agent-charges', 'Admin\Courier\VehicleAgentChargeController');
            Route::get('/vehicle-agent-charge-get-datas', 'Admin\Courier\VehicleAgentChargeController@vehicleAgentChargeGetData')->name('vehicle-agent-charge-get-datas');
            Route::get('/vehicle-agent-charge-create-datas', 'Admin\Courier\VehicleAgentChargeController@getVehicleAgentCreateData')->name('vehicle-agent-charge-create-datas');
            Route::resource('/agency-links', 'Admin\Courier\AgencyLinkController');
            Route::get('/agency-link-data', 'Admin\Courier\AgencyLinkController@agencyLinkData')->name('agency-link-data');
            Route::resource('/transit-links', 'Admin\Courier\TransitLinkController');
            Route::get('/transit-link-data', 'Admin\Courier\TransitLinkController@transitLinkData')->name('transit-link-data');
        });




        //Route Function For Terminal Point  Controll by Admin
        Route::resource('/terminalpoint', 'Admin\TerminalPointController');
        Route::resource('/packagetype', 'Admin\PackageTypeController');
        //Route Function For Package Sensitivities   Controll by Admin
        Route::resource('/packagesensitivity', 'Admin\PackageSensitivityController');
        //Route Function for Load Information COntroll by Admin
        Route::get('/fullload', 'Admin\LoadInformationController@getFillLoad')->name('fullload');
        Route::get('/partload', 'Admin\LoadInformationController@getpartload')->name('partload');
        Route::get('/partloadshow/{id}', 'Admin\LoadInformationController@getpartloadview');

        Route::resource('/shipment', 'Admin\ShipmentController'); //Shipment routes

        Route::group(['prefix' => 'transport'], function () {
            Route::resource('/medias', 'Admin\TransportMediaController'); //Transport medias 
            Route::resource('/vehicles', 'Admin\TransportVehicleController'); //Transport Vehicles
            Route::group(['prefix' => 'vehicle', 'as' => 'vehicles.'], function () {
                Route::resource('/dimensions', 'Admin\VehicleDimensionController'); //Transport Vehicles
                Route::resource('/rates', 'Admin\VehicleDimensionRateController'); //VehicleDimensionRatesController
            });
        });
        Route::resource('/departments', 'Admin\DepartmentController');    //Department routes
        Route::resource('/designations', 'Admin\DesignationController');    //Designation routes


        Route::resource('/offices', 'Admin\OfficeController');    //Office routes
        //agent office route
        Route::resource('/agency-offices', 'Admin\Office\AgentOfficeController');

        //transit office route
        Route::resource('/transit-offices', 'Admin\Office\TransitOfficeController');

        //transit office connections route
        Route::get('/transit-offices/{officeId}/connections',
            'Admin\Office\TransitOfficeController@getTransitOfficeConnections')->name('transit-offices.connections');
        Route::post('/transit-offices/{officeId}/connections/store',
            'Admin\Office\TransitOfficeController@storeConnectionOfTransit')->name('transit-offices.connections.store');
        Route::get('/transit-offices/{officeId}/connections/{transitLinkId}/edit',
            'Admin\Office\TransitOfficeController@editConnectionOfTransit')->name('transit-offices.connections.edit');
        Route::put('/transit-offices/{officeId}/connections/{transitLinkId}/edit',
            'Admin\Office\TransitOfficeController@updateConnectionOfTransit')->name('transit-offices.connections.update');
        Route::delete('/transit-offices/{officeId}/connections/{transitLinkId}/toggle-status',
            'Admin\Office\TransitOfficeController@toggleConnectionStatusOfTransit')->name('transit-offices.connections.toggleStatus');
        Route::delete('/transit-offices/{officeId}/connections/{transitLinkId}/destroy',
            'Admin\Office\TransitOfficeController@deleteConnectionOfTransit')->name('transit-offices.connections.destroy');

        //agency transit connections route by agency
        Route::get('/agency-offices/{officeId}/agency-transit-connections',
            'Admin\Office\AgencyTransitConnectionController@getTransitConnectionsOfAgency')->name('agency-transit.connections');
        Route::post('/agency-offices/{officeId}/agency-transit-connections/store',
            'Admin\Office\AgencyTransitConnectionController@storeTransitConnectionOfAgency')->name('agency-transit.connections.store');
        Route::get('/agency-offices/{agencyOfficeId}/agency-transit-connections/{transitOfficeId}/edit',
            'Admin\Office\AgencyTransitConnectionController@editTransitConnectionOfAgency')->name('agency-transit.connections.edit');
        Route::put('/agency-offices/{agencyOfficeId}/agency-transit-connections/{transitOfficeId}/edit',
            'Admin\Office\AgencyTransitConnectionController@updateTransitConnectionOfAgency')->name('agency-transit.connections.update');
        Route::delete('/agency-offices/{agencyOfficeId}/agency-transit-connections/{transitOfficeId}/toggle-status',
            'Admin\Office\AgencyTransitConnectionController@toggleTransitConnectionStatusOfAgency')->name('agency-transit.connections.toggleStatus');
        Route::delete('/agency-offices/{agencyOfficeId}/agency-transit-connections/{transitOfficeId}/destroy',
            'Admin\Office\AgencyTransitConnectionController@deleteTransitConnectionOfAgency')->name('agency-transit.connections.destroy');
        Route::resource('/roles', 'Admin\RoleController');       //Role routes

        Route::resource('/employees', 'Admin\EmployeeController');    //Employee routes

app/Http/Controllers/Admin/Office/AgencyTransitConnectionController.php
<?php

namespace App\Http\Controllers\Admin\Office;

use App\Http\Controllers\Controller;
use App\Services\OfficeService;
use App\ValidationRules\AgentOfficeRule;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

use DB;

class AgencyTransitConnectionController extends Controller
{
    private $officeService;

    public function __construct(OfficeService $officeService){
        $this->officeService = $officeService;
    }

    public function getTransitConnectionsOfAgency($officeId){

        $office = $this->officeService->findAgencyOfficeById($officeId);

        $agencyTransitConnections = $this->officeService->getTransitConnectionsOfAgency($officeId);

        //return($agencyTransitConnections);

        //for add connection form
        $transitOffices = $this->officeService->getActiveTransitOffices($officeId);

        return  view('admin.pages.office.agent-office.agency-transit-link.index',compact('office',
            'agencyTransitConnections','transitOffices'));
    }

    public function storeTransitConnectionOfAgency(Request $request,$officeId){

        $validator = Validator::make($request->all(),(new AgentOfficeRule($request))->getAgentOfficeValidationRules('addConnection',0,$officeId));
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        try{

            DB::beginTransaction();
            $this->officeService->storeTransitConnectionOfAgency($request,$officeId);
            DB::commit();
            return redirect()->back()->with('flash_message_success', 'New Connection Added Successfully!');

        }catch(\Exception $e){
            DB::rollBack();
            return redirect()->back()->with('flash_message_danger', $e->getMessage())->withInput();
        }
    }

    public function editTransitConnectionOfAgency($agencyOfficeId,$transitOfficeId){

        try{

            $transitOffice = $this->officeService->findTransitOfficeById($transitOfficeId);
            $agencyOffice = $this->officeService->findAgencyOfficeById($agencyOfficeId);

            $agencyTransitConnection = $this->officeService->findAgencyTransitConnection($agencyOffice->agency->id,$transitOffice->transit->id);

            return view('admin.pages.office.agent-office.agency-transit-link.edit',compact('agencyOffice',
                'transitOffice','agencyTransitConnection'));

        }catch(\Exception $e){
            return redirect()->back()->with('flash_message_error', $e->getMessage());
        }
    }

    public function updateTransitConnectionOfAgency(Request $request,$agencyOfficeId,$transitOfficeId){

        $validator = Validator::make($request->all(),(new AgentOfficeRule($request))->getAgentOfficeValidationRules('editConnection'));
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        try{

            DB::beginTransaction();
            $this->officeService->updateTransitConnectionOfAgency($request,$agencyOfficeId,$transitOfficeId);
            DB::commit();
            return redirect()->back()->with('flash_message_success', 'Connection Updated Successfully!');

        }catch(\Exception $e){
            DB::rollBack();
            return redirect()->back()->with('flash_message_danger', $e->getMessage())->withInput();
        }
    }

    public function toggleTransitConnectionStatusOfAgency($agencyOfficeId,$transitOfficeId){

        try{
            $this->officeService->toggleTransitConnectionStatusOfAgency($agencyOfficeId,$transitOfficeId);
            return back()->with('flash_message_success', 'Operation Completed Successfully');
        }catch(\Exception $e){
            return back()->with('flash_message_error', $e->getMessage());
        }
    }

    public function deleteTransitConnectionOfAgency($agencyOfficeId,$transitOfficeId){

        try{
            $this->officeService->deleteTransitConnectionOfAgency($agencyOfficeId,$transitOfficeId);
            return back()->with('flash_message_success', 'Connection Deleted Successfully');
        }catch(\Exception $e){
            return back()->with('flash_message_error', $e->getMessage());
        }
    }
}

resources/views/admin/pages/office/agent-office/create.blade.php
@extends('admin.layouts.app')
@section('title','Agency Offices')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.agency-offices.index')}}">Agency Offices</a></li>
    <li class="breadcrumb-item active">Create</li>
@endsection
@section('content')
    @include('error-messages.message')

    <form action="{{route('admin.agency-offices.store')}}" method="POST">
        {{ csrf_field() }}
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <div class="form-group">
                            <label class="control-label"  >Name</label>
                            <input type="text" class="form-control" name="name" value="{{old('name') }}">
                            @if ($errors->has('name')) <p style="color:red;">{{ $errors->first('name') }}</p> @endif <br>
                        </div>


                        <div class="form-group">
                            <label class="control-label"  >Address</label>
                            <input type="text" class="form-control" name="address" value="{{ old('address') }}">
                            @if ($errors->has('address')) <p style="color:red;">{{ $errors->first('address') }}</p> @endif <br>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 col-md-6">
                                <div class="form-group">
                                    <label class="control-label"  >Phone</label>
                                    <input type="text" class="form-control" name="phone" value="{{ old('phone') }}">
                                    @if ($errors->has('phone')) <p style="color:red;">{{ $errors->first('phone') }}</p> @endif <br>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <div class="form-group">
                                    <label class="control-label"  >Email</label>
                                    <input type="text" class="form-control" name="email" value="{{ old('email') }}">
                                    @if ($errors->has('email')) <p style="color:red;">{{ $errors->first('email') }}</p> @endif <br>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 col-md-6">
                                <div class="form-group">
                                    <label class="control-label"  >Latitude</label>
                                    <input type="number" step="any" class="form-control" name="latitude" value="{{ old('latitude') }}">
                                    @if ($errors->has('latitude')) <p style="color:red;">{{ $errors->first('latitude') }}</p> @endif <br>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <div class="form-group">
                                    <label class="control-label"  >Longitude</label>
                                    <input type="number" step="any" class="form-control" name="longitude" value="{{ old('longitude') }}">
                                    @if ($errors->has('longitude')) <p style="color:red;">{{ $errors->first('longitude') }}</p> @endif <br>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label" >Agency Class</label>
                            <select class="form-control select2" name="agency_class" >
                                <option selected disabled >--select an option --</option>

                                @foreach($agencyTypeCourierClasses as $courierClass)
                                    <option value="{{$courierClass->slug}}" {{old('agency_class') == $courierClass->slug ? 'selected' : ''}}>{{$courierClass->name}}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('agency_class')) <p style="color:red;">{{ $errors->first('agency_class') }}</p> @endif <br>
                        </div>

                        <div class="form-group">
                            <label class="control-label" >Working As</label>
                            <select class="form-control select2" name="working_as" >
                                <option selected disabled >--select an option --</option>

                                @foreach($agencyWorkingOptions as $optionKey => $optionValue)
                                    <option value="{{$optionValue}}" {{old('working_as') == $optionValue ? 'selected' : ''}}>{{$optionKey}}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('working_as')) <p style="color:red;">{{ $errors->first('working_as') }}</p> @endif <br>
                        </div>

                        <div class="form-group">
                            <label class="control-label" >Transit Connection</label>
                            <select class="form-control select2" name="transit_connection" >
                                <option selected disabled >--select an option --</option>

                                @foreach($transitOffices as $office)
                                    <option value="{{$office->transit->id}}" {{old('transit_connection') == $office->transit->id ? 'selected' : ''}}>{{$office->name}}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('transit_connection')) <p style="color:red;">{{ $errors->first('transit_connection') }}</p> @endif <br>
                        </div>

                        <div class="row">


                            <div class="col-sm-12 col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Distance</label>
                                    <input type="number" step="any" class="form-control" name="distance" placeholder="In Kilometer" value="{{ old('distance') }}">
                                    @if ($errors->has('distance')) <p style="color:red;">{{ $errors->first('distance') }}</p> @endif <br>
                                </div>
                            </div>



                            <div class="col-sm-12 col-md-6">
                                <div class="form-group">
                                    <label class="control-label" >Travel Time</label>
                                    <input type="number" step="any" class="form-control" name="travel_time" value="{{ old('travel_time') }}" placeholder="In hour">
                                    @if ($errors->has('travel_time')) <p style="color:red;">{{ $errors->first('travel_time') }}</p> @endif <br>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label">Select</label>
                            <div class="custom-control custom-radio p-l-0">
                                <input type="radio" class="custom-control-input" id="defaultChecked" name="status" value="1"
                                        {{ old('status') == 1 ? 'checked' : '' }}>
                                <label class="custom-control-label" for="defaultChecked">Active</label>
                            </div> 
                            <div class="custom-control custom-radio p-l-0">
                                <input type="radio" class="custom-control-input" id="defaultUnchecked" name="status" value="0"
                                        {{ (!is_null(old('status')) && old('status') == 0)  ? 'checked' : '' }}>
                                <label class="custom-control-label" for="defaultUnchecked">Deactive</label>
                            </div>
                        </div>

                        <div class="form-group">
                            <input type="submit" class="btn btn-success" value="Submit">
                        </div>

                    </div>
                </div>
            </div>
        </div>


    </form>

@endsection

resources/views/admin/pages/office/agent-office/index.blade.php
@extends('admin.layouts.app')
@section('title','Agency Offices')

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.agency-offices.index')}}">Agency Offices</a></li>
@endsection

@section('content')

    @include('error-messages.message')

    <div class="row">
        <div class="col-lg-12 text-right">
            <a href="{{route('admin.agency-offices.create')}}" class="btn btn-success m-b-10">Create</a>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive mt-4">
                        <table id="myTable" class="table">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col"> S.N </th>
                                <th scope="col"> Name </th>
                                <th scope="col">Country</th>
                                <th scope="col">Type</th>
                                <th scope="col"> Address</th>
                                <th scope="col"> Action </th>
                            </tr>
                            </thead>
                            @foreach($agencyOffices as $office)
                                <tbody>
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$office->name}}</td>
                                    <td>{{$office->country->name}}</td>
                                    <td>{{$office->office_type}}</td>
                                    <td>{{$office->address}}</td>
                                    <td class="table-flex">
                                        <a href="{{route('admin.agency-offices.show', $office->id) }}" class="btn btn-info m-r-10"><i class="fa fa-eye"></i></a>
                                        <a href="{{route('admin.agency-transit.connections',$office->id)}}" class="btn btn-info m-r-10"><i class="fa fa-link" title="connections"></i></a>
                                        <a href="{{route('admin.agency-offices.edit', $office->id)}}" class="btn btn-warning m-r-10"><i class="far fa-edit"></i></a>

                                        <form action="{{ route('admin.agency-offices.destroy',$office->id)}}" method="post">
                                            {{ csrf_field() }}
                                            @method('DELETE')
                                            @if($office->status==0)
                                                <button type="submit" class="btn btn-success">Activate</button>
                                            @else
                                                <button type="submit" class="btn btn-danger">Deactivate</button>
                                            @endif
                                        </form>
                                    </td>
                                </tr>
                                </tbody>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>



@endsection

resources/views/admin/pages/office/agent-office/show.blade.php
@extends('admin.layouts.app')
@section('title','Agency Offices')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.agency-offices.index')}}">Agency Offices</a></li>
    <li class="breadcrumb-item active">{{$office->name}}</li>
@endsection
@section('content')
    <div class="row">
        <div class="col-lg-12 text-right">
            <a href="{{route('admin.agency-offices.create')}}" class="btn btn-success m-b-10">Create</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">

                            <tr>
                                <th>Name</th>
                                <td>{{$office->name}}</td>
                            </tr>
                            <tr>
                                <th>Country</th>
                                <td>{{$office->country->name}}</td>
                            </tr>
                            <tr>
                                <th>Office Type</th>
                                <td>{{$office->office_type}}</td>
                            </tr>
                            <tr>
                                <th>Working As</th>
                                <td>{{$office->agency->working_as}}</td>
                            </tr>
                            <tr>
                                <th>Class</th>
                                <td>
                                    <a href="{{route('admin.courier-classes.show',$office->agency->agencyClass->id)}}">
                                        {{$office->agency->agencyClass->name}}
                                    </a>

                                </td>
                            </tr>
                            <tr>
                                <th>Address</th>
                                <td>{{$office->address}}</td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td>
                                    @if($office->status == 1)
                                        <span style ="color:red"> Activated</span>
                                    @else
                                        <span style ="color:blue"> Deactivated</span>
                                    @endif
                                </td>
                            </tr>

                            <tr>
                                <th>Created By</th>
                                <td>{{$office->createdBy->user->name}}</td>
                            </tr>

                            <tr>
                                <th>Updated By</th>
                                <td>{{$office->updatedBy->user->name}}</td>
                            </tr>
                        </table>
                    </div>

                    <div class="form-btn" >
                        <a href="{{ route('admin.agency-offices.edit', $office->id) }}" class="btn btn-warning">Edit</a>

                        <form action="{{ route('admin.agency-offices.destroy', $office->id)}}" method="post">
                            {{ csrf_field() }}
                            @method('DELETE')
                            @if($office->status==0)
                                <button type="submit" class="btn btn-success">Activate</button>
                            @else
                                <button type="submit" class="btn btn-danger">Deactivate</button>
                            @endif
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>

@endsection