routes/web.php
        Route::group(['prefix'=>'courier'], function(){
            Route::group(['prefix'=>'quantity', 'as' =>'quantity.'], function(){
                Route::resource('/ranges','Admin\Courier\QuantityGroupRangeController');
                Route::resource('/groups', 'Admin\Courier\QuantityGroupController');
                // Route::get('quantity-group-country-show/{coId}/{qaId}', 'Admin\Courier\QuantityGroupCountryController@quantityGroupCountryShow')->name('quantity-group-country-show');
                // Route::get('quantity-group-country-edit/{coId}/{qaId}', 'Admin\Courier\QuantityGroupCountryController@quantityGroupCountryEdit')->name('quantity-group-country-edit');
            });

            Route::resource('/vehicle-time-range', 'Admin\Courier\VehicleTimeTravelRangeController');
            
            // Route::resource('/time-travel-groups', 'Admin\Courier\TimeTravelGroupController');
            // Route::resource('/time-travel-group-rates', 'Admin\Courier\TimeTravelGroupRateController');
            // Route::get('/create-time-travel-group-rate', 'Admin\Courier\TimeTravelGroupRateController@timeTravelGroupData')->name('create-time-travel-group-rate');
            Route::resource('/airports', 'Admin\Courier\AirportController');
            Route::get('/airport-links/getdatacountryone', 'Admin\Courier\AirportLinkController@getDataCountryOne')->name('airport-links.getdatacountryone');
            Route::get('/airport-links/getdatacountrytwo', 'Admin\Courier\AirportLinkController@getDataCountryTwo')->name('airport-links.getdatacountrytwo');
            Route::resource('/airport-links', 'Admin\Courier\AirportLinkController');
            Route::get('/airport-charges/getQuantityGroupRange', 'Admin\Courier\AirportChargeController@getQuantityGroupRangedata')->name('airport-charges.getQuantityGroupRange');
            Route::resource('/airport-charges', 'Admin\Courier\AirportChargeController');
            Route::get('/get-airport-data', 'Admin\Courier\AirportLinkController@getAirpotData')->name('get-airport-data');
            Route::group(['prefix' => 'class', 'as' => 'class.'], function () {
                Route::resource('agencies', 'Admin\Courier\AgencyClassController');

         

                Route::resource('transits', 'Admin\Courier\TransitClassController');
                Route::group(['prefix' => 'charge', 'as' => 'charge.'], function () {
                    Route::resource('agencies', 'Admin\Courier\AgencyClassChargeController');
                    Route::get('/get-quantity-group-data', 'Admin\Courier\AgencyClassChargeController@getQuanityGroupData')->name('get-quantity-group-data');
                    Route::resource('transits', 'Admin\Courier\TransitClassChargeController');
                    Route::get('/get-transit-quantity-group-range', 'Admin\Courier\TransitClassChargeController@getQuanityGroupRange')->name('get-transit-quantity-group-range');
                    Route::get('/get-agency-quantity-group-range', 'Admin\Courier\AgencyClassChargeController@getQuanityGroupRange')->name('get-agency-quantity-group-range');
                });

            });
            Route::get('/agency-transit-vehicle-charge/getQuantityGroupRange', 'Admin\Courier\AgencyTransitVehicleChargeController@getQuantityGroupRangedata')->name('agency-transit-vehicle-charge.getQuantityGroupRange');
            Route::resource('/agency-transit-vehicle-', 'Admin\Courier\AgencyTransitVehicleChargeController');
            Route::resource('/services', 'Admin\Courier\ServiceController');
            Route::get('/admin-charges/getQuantityGroupRange', 'Admin\Courier\AdminChargerController@getQuantityGroupRangedata')->name('admin-charges.getQuantityGroupRange');
            Route::resource('/admin-charges', 'Admin\Courier\AdminChargerController');
            Route::get('/admin-create-charge', 'Admin\Courier\AdminChargerController@adminChargeCreate')->name('admin-create-charge');
            Route::resource('/transits', 'Admin\Courier\TransitController');
            Route::resource('transit-charges', 'Admin\Courier\TransitChargeController');
            Route::resource('transit-vehicle-charges', 'Admin\Courier\TransitVehicleChargeController');

            Route::resource('/agencies', 'Admin\Courier\AgencyController');
            Route::resource('/vehicle-agent-charges', 'Admin\Courier\VehicleAgentChargeController');
            Route::get('/vehicle-agent-charge-get-datas', 'Admin\Courier\VehicleAgentChargeController@vehicleAgentChargeGetData')->name('vehicle-agent-charge-get-datas');
            Route::get('/vehicle-agent-charge-create-datas', 'Admin\Courier\VehicleAgentChargeController@getVehicleAgentCreateData')->name('vehicle-agent-charge-create-datas');
            Route::resource('/agency-links', 'Admin\Courier\AgencyLinkController');
            Route::get('/agency-link-data', 'Admin\Courier\AgencyLinkController@agencyLinkData')->name('agency-link-data');
            Route::resource('/transit-links', 'Admin\Courier\TransitLinkController');
            Route::get('/transit-link-data', 'Admin\Courier\TransitLinkController@transitLinkData')->name('transit-link-data');
        });




        //Route Function For Terminal Point  Controll by Admin
        Route::resource('/terminalpoint', 'Admin\TerminalPointController');
        Route::resource('/packagetype', 'Admin\PackageTypeController');
        //Route Function For Package Sensitivities   Controll by Admin
        Route::resource('/packagesensitivity', 'Admin\PackageSensitivityController');
        //Route Function for Load Information COntroll by Admin
        Route::get('/fullload', 'Admin\LoadInformationController@getFillLoad')->name('fullload');
        Route::get('/partload', 'Admin\LoadInformationController@getpartload')->name('partload');
        Route::get('/partloadshow/{id}', 'Admin\LoadInformationController@getpartloadview');

        Route::resource('/shipment', 'Admin\ShipmentController'); //Shipment routes

        Route::group(['prefix' => 'transport'], function () {
            Route::resource('/medias', 'Admin\TransportMediaController'); //Transport medias 
            Route::resource('/vehicles', 'Admin\TransportVehicleController'); //Transport Vehicles
            Route::group(['prefix' => 'vehicle', 'as' => 'vehicles.'], function () {
                Route::resource('/dimensions', 'Admin\VehicleDimensionController'); //Transport Vehicles
                Route::resource('/rates', 'Admin\VehicleDimensionRateController'); //VehicleDimensionRatesController
            });
        });
        Route::resource('/departments', 'Admin\DepartmentController');    //Department routes
        Route::resource('/designations', 'Admin\DesignationController');    //Designation routes


        Route::resource('/offices', 'Admin\OfficeController');    //Office routes
        //agent office route
        Route::resource('/agency-offices', 'Admin\Office\AgentOfficeController');

        //transit office route
        Route::resource('/transit-offices', 'Admin\Office\TransitOfficeController');

        //transit office connections route
        Route::get('/transit-offices/{officeId}/connections',
            'Admin\Office\TransitOfficeController@getTransitOfficeConnections')->name('transit-offices.connections');
        Route::post('/transit-offices/{officeId}/connections/store',
            'Admin\Office\TransitOfficeController@storeConnectionOfTransit')->name('transit-offices.connections.store');
        Route::get('/transit-offices/{officeId}/connections/{transitLinkId}/edit',
            'Admin\Office\TransitOfficeController@editConnectionOfTransit')->name('transit-offices.connections.edit');
        Route::put('/transit-offices/{officeId}/connections/{transitLinkId}/edit',
            'Admin\Office\TransitOfficeController@updateConnectionOfTransit')->name('transit-offices.connections.update');
        Route::delete('/transit-offices/{officeId}/connections/{transitLinkId}/toggle-status',
            'Admin\Office\TransitOfficeController@toggleConnectionStatusOfTransit')->name('transit-offices.connections.toggleStatus');
        Route::delete('/transit-offices/{officeId}/connections/{transitLinkId}/destroy',
            'Admin\Office\TransitOfficeController@deleteConnectionOfTransit')->name('transit-offices.connections.destroy');

        //agency transit connections route by agency
        Route::get('/agency-offices/{officeId}/agency-transit-connections',
            'Admin\Office\AgencyTransitConnectionController@getTransitConnectionsOfAgency')->name('agency-transit.connections');
        Route::post('/agency-offices/{officeId}/agency-transit-connections/store',
            'Admin\Office\AgencyTransitConnectionController@storeTransitConnectionOfAgency')->name('agency-transit.connections.store');
        Route::get('/agency-offices/{agencyOfficeId}/agency-transit-connections/{transitOfficeId}/edit',
            'Admin\Office\AgencyTransitConnectionController@editTransitConnectionOfAgency')->name('agency-transit.connections.edit');
        Route::put('/agency-offices/{agencyOfficeId}/agency-transit-connections/{transitOfficeId}/edit',
            'Admin\Office\AgencyTransitConnectionController@updateTransitConnectionOfAgency')->name('agency-transit.connections.update');
        Route::delete('/agency-offices/{agencyOfficeId}/agency-transit-connections/{transitOfficeId}/toggle-status',
            'Admin\Office\AgencyTransitConnectionController@toggleTransitConnectionStatusOfAgency')->name('agency-transit.connections.toggleStatus');
        Route::delete('/agency-offices/{agencyOfficeId}/agency-transit-connections/{transitOfficeId}/destroy',
            'Admin\Office\AgencyTransitConnectionController@deleteTransitConnectionOfAgency')->name('agency-transit.connections.destroy');
        Route::resource('/roles', 'Admin\RoleController');       //Role routes

        Route::resource('/employees', 'Admin\EmployeeController');    //Employee routes

app/Models/Designation.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Designation extends Model
{
    protected $fillable = ['title', 'slug', 'status', 'description', 'created_by', 'updated_by', 'created_at', 'updated_at'];

    //get employees  for the designation
    public function employees(){
        return $this->hasMany(Employee::class,'designation_id');
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }

    public static function getActiveDesignations(){
        return self::active()->get();
    }
}

app/Http/Controllers/Admin/DesignationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Repositories\Designation\DesignationInterface;
use Illuminate\Http\Request;
use App\ValidationRules\DesignationRule;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class DesignationController extends Controller
{
    protected $designationRepo;
    public function __construct(DesignationInterface $designationRepo){
        $this->designationRepo = $designationRepo;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $designations = $this->designationRepo->all();
        return view('admin.pages.designation.index')->with('designations', $designations);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.designation.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),(new DesignationRule($request))->getDesignationValidationRules('create'));
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        $data=$request->except('_token');
        $data['slug']= Str::slug($data['title'] , '-');
        $designation=$this->designationRepo->save($data);
        if($designation){
            return redirect()->route('admin.designations.index')->with('flash_message_success', 'Designation Created Successfuly!');
        }
        else{
            return redirect()->route('admin.designations.index')->with('flash_message_error', 'Error!!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $designation = $this->designationRepo->find($id);
        return view('admin.pages.designation.show')->with('designation', $designation);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $designation = $this->designationRepo->find($id);
        return view('admin.pages.designation.edit')->with('designation', $designation);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),(new DesignationRule($request))->getDesignationValidationRules('update'));
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        $data=$request->except('_token');
        $data['slug']= Str::slug($data['title'] , '-');
        $designation=$this->designationRepo->update($data, $id);
        if($designation){
            return redirect()->route('admin.designations.index')->with('flash_message_success', 'Designation Updated Successfuly!');
        }
        else{
            return redirect()->route('admin.designations.index')->with('flash_message_error', 'Error!!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->designationRepo->changeStatus($id);
        return back()->with('flash_message_success', 'Operation Completed Successfully');
    }
}

resources/views/admin/pages/designation/create.blade.php
@extends('admin.layouts.app')
@section('title','Designations')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.designations.index')}}">Designations</a></li>
    <li class="breadcrumb-item active">Create</li>
@endsection
@section('content')
    
    <form action="{{route('admin.designations.store')}}" method="POST">
        {{ csrf_field() }}
        @include('admin.pages.designation.form', [$formMode="Publish"])
    </form>

@endsection

resources/views/admin/pages/designation/edit.blade.php
@extends('admin.layouts.app')
@section('title','Designations')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.designations.index')}}">Designations</a></li>
    <li class="breadcrumb-item active">Edit</li>
@endsection
@section('content')

    <form action="{{route('admin.designations.update', $designation->id)}}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="PUT">
        @include('admin.pages.designation.form', [$formMode="Edit"])
    </form>
        
@endsection

resources/views/admin/pages/designation/form.blade.php
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <label class="control-label"  >Name</label>
                    <input type="text" class="form-control" name="title" value="{{ isset($designation) ? $designation->title : old('title') }}">
                    @if ($errors->has('title')) <p style="color:red;">{{ $errors->first('title') }}</p> @endif <br>
                </div>
            
                <div class="form-group">
                    <label class="control-label" >Description</label>
                    <textarea class="form-control" rows="5" cols="10" name="description">{{ isset($designation) ? $designation->description : old('description') }}</textarea>
                    @if ($errors->has('description')) <p style="color:red;">{{ $errors->first('description') }}</p> @endif <br>
                </div>
            
                <div class="form-group">
                    <label class="control-label">Select</label>
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="defaultChecked" name="status" value="1" {{ isset($designation) && $designation->status == 1 ? 'checked' : '' }}>
                        <label class="custom-control-label" for="defaultChecked">Active</label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" id="defaultUnchecked" name="status" value="0" {{ isset($designation) && $designation->status == 0 ? 'checked' : '' }}>
                        <label class="custom-control-label" for="defaultUnchecked">Deactive</label>
                    </div>
                </div>
            
                <div class="form-group">
                <input type="submit" class="btn btn-success"
                value="{{ $formMode == 'Publish' ? 'Publish' : 'Update'}}">
                </div>
            </div>
        </div>
    </div>
</div>
    

resources/views/admin/pages/designation/index.blade.php
@extends('admin.layouts.app')
@section('title','Designations')

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.designations.index')}}">Designations</a></li>
@endsection

@section('content')

@include('error-messages.message')

<div class="row">
    <div class="col-lg-12 text-right">
        <a href="{{route('admin.designations.create')}}" class="btn btn-success m-b-10">Create</a>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive mt-4">
                    <table id="myTable" class="table">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col"> ID </th>
                            <th scope="col"> Name </th>
                            <th scope="col"> Description </th>
                            <th scope="col"> Action </th>
                        </tr>
                        </thead>
                        @foreach($designations as $designation)
                            <tbody>
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$designation->title}}</td>
                                <td>{{$designation->description}}</td>
                                <td class="table-flex">
                                    <a href="{{route('admin.designations.show', $designation->id) }}" class="btn btn-info m-r-10"><i class="fa fa-eye"></i></a>
                                    <a href="{{route('admin.designations.edit', $designation->id)}}" class="btn btn-warning m-r-10"><i class="far fa-edit"></i></a>
                                    <form action="{{ route('admin.designations.destroy', $designation->id)}}" method="post">
                                        {{ csrf_field() }}
                                        @method('DELETE')
                                        @if($designation->status==0)

                                        <button type="submit" class="btn btn-danger">Activate</button>
                                        @else
                                            <button type="submit" class="btn btn-danger">Deactivate</button>
                                        @endif
                                    </form>
                                </td>

                            </tr>
                            </tbody>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
    

    
@endsection

resources/views/admin/pages/designation/show.blade.php
@extends('admin.layouts.app')
@section('title','Designations')
@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{url('admin')}}">Home</a></li>
<li class="breadcrumb-item"><a href="{{route('admin.designations.index')}}">Designations</a></li>
<li class="breadcrumb-item active">{{$designation->title}}</li>
@endsection
@section('content')
<div class="row">
    <div class="col-lg-12 text-right">
        <a href="{{route('admin.designations.create')}}" class="btn btn-success m-b-10">Create</a>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <!-- <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <th>Name</th>
                            <td>{{$designation->title}}</td>
                        </tr>
                        <tr>
                            <th>Description</th>
                            <td>{{$designation->description}}</td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td>
                                @if($designation->status == 1)
                                <span> Activated</span>
                                @else
                                <span> Deactivated</span>
                                @endif
                            </td>
                        </tr>

                    </table>
                </div> -->
                <div class="country-div-list">
                    <ul>
                        <li>
                            <h4>Name : </h4>
                            <h6>{{$designation->title}}</h6>
                        </li>
                        <li>
                            <h4>Description : </h4>
                            <h6>{{$designation->description}}</h6>
                        </li>
                        <li>
                            <h4>Status : </h4>
                            <h6>
                                @if($designation->status == 1)
                                <span> Activated</span>
                                @else
                                <span> Deactivated</span>
                                @endif
                            </h6>
                        </li> 
                    </ul>
                </div>

                <div class="form-btn">
                    <a href="{{ route('admin.designations.edit', $designation->id) }}" class="btn btn-warning">Edit</a>
                    <form action="{{ route('admin.designations.destroy', $designation->id)}}" method="post">
                        {{ csrf_field() }}
                        @method('DELETE')
                        @if($designation->status==0)
                        <button type="submit" class="btn btn-success">Activate</button>
                        @else
                        <button type="submit" class="btn btn-danger">Deactivate</button>
                        @endif
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection